name: Step 0 # Start Exercise

on:
  push:
    branches:
      - main

permissions:
  contents: write
  actions: write
  issues: write

env:
  STEP_1_FILE: ".github/steps/1-preparing.md"

jobs:
  start_exercise:
    if: |
      !github.event.repository.is_template
    name: Start Exercise
    uses: skills/exercise-toolkit/.github/workflows/start-exercise.yml@v0.7.0
    with:
      exercise-title: "Getting Started with GitHub Copilot"
      intro-message: "Welcome to the exciting world of GitHub Copilot! 🚀 In this exercise, you'll unlock the potential of this AI-powered coding assistant to accelerate your development process. Let's dive in and have some fun exploring the future of coding together! 💻✨"

  post_next_step_content:
    name: Post next step content
    # needs: [start_exercise]
    uses: ./.github/workflows/step-transition.yml
    with:
      current_step_number: 0
      next_step_number: 1
      is_final_step: false
      issue_number: ${{ needs.start_exercise.outputs.issue-number }}
      issue_repository: ${{ github.repository }}
      content_file: ".github/steps/1-preparing.md"
      content_vars: |
        login: ${{ github.actor }}
        full_repo_name: ${{ github.repository }}
