name: Step 1 # Preparing to make your extension

on:
  push:
    branches:
      - "accelerate-with-copilot"

permissions:
  contents: read
  actions: write
  issues: write

env:
  STEP_2_FILE: ".github/steps/2-first-introduction.md"

jobs:
  find_exercise:
    name: Find Exercise Issue
    uses: skills/exercise-toolkit/.github/workflows/find-exercise-issue.yml@v0.7.0

  post_next_step_content:
    name: Post next step content
    # needs: [find_exercise]
    uses: ./.github/workflows/step-transition.yml
    with:
      current_step_number: 1
      next_step_number: 2
      is_final_step: false
      issue_number: ${{ needs.find_exercise.outputs.issue-number }}
      issue_repository: ${{ github.repository }}
      content_file: ".github/steps/2-first-introduction.md"
